export type ScriptureTheme =
  | "home"
  | "mercy"
  | "character"
  | "trial"
  | "work"
  | "holiness"
  | "faith"
  | "brotherhood"
  | "speech"
  | "wisdom";

export type ScriptureEntry = {
  id: string;
  reference: string;
  kjv: string;
  /** Reina-Valera (public domain). Do not invent or machine-translate this. */
  es: string;
  /** Almeida (public domain). Do not invent or machine-translate this. */
  pt: string;
  keywords: string[];
  theme: ScriptureTheme;
};

/** Public-domain KJV. Verse wording stays here — generators must not invent it. */
export const SCRIPTURE_CATALOG: ScriptureEntry[] = [
  {
    id: "eph-5-25",
    reference: "Ephesians 5:25",
    kjv: "Husbands, love your wives, even as Christ also loved the church, and gave himself for it.",
    es: "Maridos, amad a vuestras mujeres, así como Cristo amó a la iglesia, y se entregó a sí mismo por ella.",
    pt: "Vós, maridos, amai vossas mulheres, como também Cristo amou a igreja, e a si mesmo se entregou por ela.",
    keywords: [
      "head of the household",
      "head of household",
      "head of the house",
      "husband",
      "husbands",
      "wife",
      "wives",
      "marriage",
      "household",
      "house",
      "home",
      "family",
      "head",
    ],
    theme: "home",
  },
  {
    id: "eph-5-23",
    reference: "Ephesians 5:23",
    kjv: "For the husband is the head of the wife, even as Christ is the head of the church: and he is the saviour of the body.",
    es: "Porque el marido es cabeza de la mujer, así como Cristo es cabeza de la iglesia, la cual es su cuerpo, y él es su Salvador.",
    pt: "Porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja, sendo ele próprio o salvador do corpo.",
    keywords: ["head", "husband", "wife", "church", "household", "leadership", "home"],
    theme: "home",
  },
  {
    id: "josh-24-15",
    reference: "Joshua 24:15",
    kjv: "And if it seem evil unto you to serve the Lord, choose you this day whom ye will serve; whether the gods which your fathers served that were on the other side of the flood, or the gods of the Amorites, in whose land ye dwell: but as for me and my house, we will serve the Lord.",
    es: "Y si mal os parece servir a Jehová, escogeos hoy a quién sirváis; si a los dioses a quienes sirvieron vuestros padres, cuando estuvieron al otro lado del río, o a los dioses de los amorreos en cuya tierra habitáis; pero yo y mi casa serviremos a Jehová.",
    pt: "Porém, se vos parece mal aos vossos olhos servir ao Senhor, escolhei hoje a quem sirvais; se aos deuses a quem serviram vossos pais, que estavam além do rio, ou aos deuses dos amorreus, em cuja terra habitais; porém eu e a minha casa serviremos ao Senhor.",
    keywords: ["house", "home", "household", "family", "serve", "choose", "joshua"],
    theme: "home",
  },
  {
    id: "1tim-3-4",
    reference: "1 Timothy 3:4",
    kjv: "One that ruleth well his own house, having his children in subjection with all gravity;",
    es: "que gobierne bien su casa, que tenga sus hijos en sujeción con toda honestidad;",
    pt: "Que governe bem a sua própria casa, tendo seus filhos em sujeição, com toda a gravidade;",
    keywords: ["rule", "house", "household", "children", "father", "home", "family"],
    theme: "home",
  },
  {
    id: "eph-6-4",
    reference: "Ephesians 6:4",
    kjv: "And, ye fathers, provoke not your children to wrath: but bring them up in the nurture and admonition of the Lord.",
    es: "Y vosotros, padres, no provoquéis a ira a vuestros hijos, sino criadlos en disciplina y amonestación del Señor.",
    pt: "E vós, pais, não provoqueis a ira a vossos filhos, mas criai-os na doutrina e admoestação do Senhor.",
    keywords: ["father", "fathers", "children", "kids", "parent", "parenting", "nurture"],
    theme: "home",
  },
  {
    id: "col-3-19",
    reference: "Colossians 3:19",
    kjv: "Husbands, love your wives, and be not bitter against them.",
    es: "Maridos, amad a vuestras mujeres, y no seáis ásperos con ellas.",
    pt: "Vós, maridos, amai a vossas mulheres, e não vos irriteis contra elas.",
    keywords: ["husband", "wife", "marriage", "bitter", "bitterness"],
    theme: "home",
  },
  {
    id: "gen-2-24",
    reference: "Genesis 2:24",
    kjv: "Therefore shall a man leave his father and his mother, and shall cleave unto his wife: and they shall be one flesh.",
    es: "Por tanto, dejará el hombre a su padre y a su madre, y se unirá a su mujer, y serán una sola carne.",
    pt: "Portanto deixará o homem o seu pai e a sua mãe, e apegar-se-á à sua mulher, e serão ambos uma carne.",
    keywords: ["marriage", "wife", "cleave", "one flesh", "wedding"],
    theme: "home",
  },
  {
    id: "matt-6-14",
    reference: "Matthew 6:14",
    kjv: "For if ye forgive men their trespasses, your heavenly Father will also forgive you.",
    es: "Porque si perdonareis a los hombres sus ofensas, os perdonará también a vosotros vuestro Padre celestial.",
    pt: "Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celestial vos perdoará a vós.",
    keywords: ["forgive", "forgiveness", "mercy", "trespass", "grace"],
    theme: "mercy",
  },
  {
    id: "col-3-13",
    reference: "Colossians 3:13",
    kjv: "Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye.",
    es: "soportándoos unos a otros, y perdonándoos unos a otros si alguno tuviere queja contra otro. De la manera que Cristo os perdonó, así también hacedlo vosotros.",
    pt: "Suportando-vos uns aos outros, e perdoando-vos uns aos outros, se alguém tiver queixa contra outro; assim como Cristo vos perdoou, assim fazei vós também.",
    keywords: ["forgive", "forgiving", "quarrel", "mercy", "forbear"],
    theme: "mercy",
  },
  {
    id: "micah-6-8",
    reference: "Micah 6:8",
    kjv: "He hath shewed thee, O man, what is good; and what doth the Lord require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?",
    es: "Oh hombre, él te ha declarado lo que es bueno, y qué pide Jehová de ti: solamente hacer justicia, y amar misericordia, y humillarte para andar con tu Dios.",
    pt: "Ele te declarou, ó homem, o que é bom; e que é o que o Senhor pede de ti, senão que pratiques a justiça, e ames a beneficência, e andes humildemente com o teu Deus?",
    keywords: ["justice", "mercy", "humble", "humility", "require", "walk"],
    theme: "character",
  },
  {
    id: "prov-10-9",
    reference: "Proverbs 10:9",
    kjv: "He that walketh uprightly walketh surely: but he that perverteth his ways shall be known.",
    es: "El que camina en integridad anda confiado; mas el que pervierte sus caminos será quebrantado.",
    pt: "Quem anda em integridade anda seguro, mas o que perverte os seus caminhos será conhecido.",
    keywords: ["integrity", "upright", "honest", "honesty", "character"],
    theme: "character",
  },
  {
    id: "prov-16-32",
    reference: "Proverbs 16:32",
    kjv: "He that is slow to anger is better than the mighty; and he that ruleth his spirit than he that taketh a city.",
    es: "Mejor es el que tarda en airarse que el fuerte; y el que se enseñorea de su espíritu, que el que toma una ciudad.",
    pt: "Melhor é o longânimo do que o valente, e o que governa o seu espírito do que o que toma uma cidade.",
    keywords: ["anger", "temper", "self-control", "self control", "spirit", "patience"],
    theme: "character",
  },
  {
    id: "1cor-16-13",
    reference: "1 Corinthians 16:13",
    kjv: "Watch ye, stand fast in the faith, quit you like men, be strong.",
    es: "Velad, estad firmes en la fe; portaos varonilmente, y esforzaos.",
    pt: "Vigiai, estai firmes na fé; portai-vos varonilmente, e fortalecei-vos.",
    keywords: ["courage", "strong", "men", "manhood", "stand", "watch"],
    theme: "character",
  },
  {
    id: "josh-1-9",
    reference: "Joshua 1:9",
    kjv: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.",
    es: "Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que fueres.",
    pt: "Não to mandei eu? Esforça-te, e tem bom ânimo; não pasmes, nem te espantes, porque o Senhor teu Deus é contigo, por onde quer que andares.",
    keywords: ["courage", "fear", "afraid", "strong", "joshua"],
    theme: "character",
  },
  {
    id: "col-3-23",
    reference: "Colossians 3:23",
    kjv: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men.",
    es: "Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres.",
    pt: "E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor, e não aos homens.",
    keywords: ["work", "job", "labor", "labour", "workplace", "diligence"],
    theme: "work",
  },
  {
    id: "prov-14-23",
    reference: "Proverbs 14:23",
    kjv: "In all labour there is profit: but the talk of the lips tendeth only to penury.",
    es: "En toda labor hay fruto; mas el hablar de los labios solo alcanza pobreza.",
    pt: "Em todo trabalho há proveito, mas meras palavras encaminham para a penúria.",
    keywords: ["work", "labour", "labor", "profit", "idle", "talk"],
    theme: "work",
  },
  {
    id: "james-1-2",
    reference: "James 1:2-3",
    kjv: "My brethren, count it all joy when ye fall into divers temptations; knowing this, that the trying of your faith worketh patience.",
    es: "Hermanos míos, tened por sumo gozo cuando os halléis en diversas pruebas, sabiendo que la prueba de vuestra fe produce paciencia.",
    pt: "Meus irmãos, tende por motivo de grande gozo o passardes por várias provações, sabendo que a prova da vossa fé produz a paciência.",
    keywords: ["trial", "trials", "testing", "patience", "suffering", "hardship"],
    theme: "trial",
  },
  {
    id: "rom-8-28",
    reference: "Romans 8:28",
    kjv: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
    es: "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados.",
    pt: "E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados por seu decreto.",
    keywords: ["purpose", "suffering", "all things", "good", "called"],
    theme: "trial",
  },
  {
    id: "phil-4-6",
    reference: "Philippians 4:6-7",
    kjv: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
    es: "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con hacimiento de gracias. Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.",
    pt: "Não estejais inquietos por coisa alguma; antes as vossas petições sejam em tudo conhecidas diante de Deus pela oração e súplica, com ação de graças. E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus.",
    keywords: ["anxiety", "worry", "peace", "prayer", "careful", "stress"],
    theme: "trial",
  },
  {
    id: "heb-13-5",
    reference: "Hebrews 13:5",
    kjv: "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee.",
    es: "Sean las costumbres vuestras sin avaricia, contentos con lo que tenéis ahora; porque él dijo: No te desampararé, ni te dejaré.",
    pt: "Sejam vossos costumes sem avareza, contentando-vos com o que tendes; porque ele disse: Não te deixarei, nem te desampararei.",
    keywords: ["content", "contentment", "covet", "money", "enough"],
    theme: "faith",
  },
  {
    id: "matt-6-33",
    reference: "Matthew 6:33",
    kjv: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
    es: "Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.",
    pt: "Mas, buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas.",
    keywords: ["priority", "first", "kingdom", "seek", "money", "provision"],
    theme: "faith",
  },
  {
    id: "prov-3-5",
    reference: "Proverbs 3:5-6",
    kjv: "Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.",
    es: "Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia. Reconócelo en todos tus caminos, y él enderezará tus veredas.",
    pt: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.",
    keywords: ["trust", "wisdom", "guidance", "direction", "lean", "paths"],
    theme: "wisdom",
  },
  {
    id: "james-1-22",
    reference: "James 1:22",
    kjv: "But be ye doers of the word, and not hearers only, deceiving your own selves.",
    es: "Mas sed hacedores de la palabra, y no tan solamente oidores, engañándoos a vosotros mismos.",
    pt: "E sede cumpridores da palavra, e não somente ouvintes, enganando-vos a vós mesmos.",
    keywords: ["doers", "word", "obedience", "hearers", "bible", "scripture"],
    theme: "wisdom",
  },
  {
    id: "ps-119-105",
    reference: "Psalm 119:105",
    kjv: "Thy word is a lamp unto my feet, and a light unto my path.",
    es: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino.",
    pt: "Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho.",
    keywords: ["word", "bible", "scripture", "lamp", "path", "guidance"],
    theme: "wisdom",
  },
  {
    id: "1thess-4-3",
    reference: "1 Thessalonians 4:3-4",
    kjv: "For this is the will of God, even your sanctification, that ye should abstain from fornication: that every one of you should know how to possess his vessel in sanctification and honour;",
    es: "Porque la voluntad de Dios es vuestra santificación; que os apartéis de fornicación; que cada uno de vosotros sepa tener su vaso en santificación y honor;",
    pt: "Porque esta é a vontade de Deus, a vossa santificação: que vos abstenhais da prostituição; Que cada um de vós saiba possuir o seu vaso em santificação e honra;",
    keywords: ["purity", "lust", "sexual", "sanctification", "fornication", "honor", "honour"],
    theme: "holiness",
  },
  {
    id: "2tim-2-22",
    reference: "2 Timothy 2:22",
    kjv: "Flee also youthful lusts: but follow righteousness, faith, charity, peace, with them that call on the Lord out of a pure heart.",
    es: "Huye también de los deseos juveniles, y sigue la justicia, la fe, la caridad, la paz, con los que invocan al Señor de puro corazón.",
    pt: "Foge também das paixões da mocidade; e segue a justiça, a fé, o amor, e a paz com os que, com um coração puro, invocam o Senhor.",
    keywords: ["lust", "flee", "purity", "youth", "temptation"],
    theme: "holiness",
  },
  {
    id: "prov-27-17",
    reference: "Proverbs 27:17",
    kjv: "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.",
    es: "Hierro con hierro se aguza; y así el hombre aguza el rostro de su amigo.",
    pt: "Como o ferro com o ferro se aguça, assim o homem afia o rosto do seu amigo.",
    keywords: ["brotherhood", "friend", "iron", "sharpen", "accountability"],
    theme: "brotherhood",
  },
  {
    id: "ecc-4-9",
    reference: "Ecclesiastes 4:9-10",
    kjv: "Two are better than one; because they have a good reward for their labour. For if they fall, the one will lift up his fellow: but woe to him that is alone when he falleth; for he hath not another to help him up.",
    es: "Mejores son dos que uno; porque tienen mejor paga de su trabajo. Porque si cayeren, el uno levantará a su compañero; pero ¡ay del solo! que cuando cayere, no habrá segundo que lo levante.",
    pt: "Melhor é serem dois do que um, porque têm melhor paga do seu trabalho. Porque se um cair, o outro levanta o seu companheiro; mas ai do que estiver só; pois, caindo, não haverá outro que o levante.",
    keywords: ["accountability", "alone", "two", "together", "fall"],
    theme: "brotherhood",
  },
  {
    id: "mark-10-45",
    reference: "Mark 10:45",
    kjv: "For even the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many.",
    es: "Porque el Hijo del Hombre no vino para ser servido, sino para servir, y para dar su vida en rescate por muchos.",
    pt: "Porque o Filho do homem também não veio para ser servido, mas para servir e dar a sua vida em resgate de muitos.",
    keywords: ["serve", "servant", "leadership", "minister", "ransom"],
    theme: "brotherhood",
  },
  {
    id: "eph-4-29",
    reference: "Ephesians 4:29",
    kjv: "Let no corrupt communication proceed out of your mouth, but that which is good to the use of edifying, that it may minister grace unto the hearers.",
    es: "Ninguna palabra torpe salga de vuestra boca, sino la que sea buena para la necesaria edificación, para que dé gracia a los oyentes.",
    pt: "Não saia da vossa boca nenhuma palavra torpe, mas só a que for boa para promover a edificação, para que dê graça aos que a ouvem.",
    keywords: ["speech", "mouth", "words", "talk", "edify", "language"],
    theme: "speech",
  },
  {
    id: "james-1-19",
    reference: "James 1:19",
    kjv: "Wherefore, my beloved brethren, let every man be swift to hear, slow to speak, slow to wrath:",
    es: "Por esto, mis amados hermanos, todo hombre sea pronto para oír, tardo para hablar, tardo para airarse:",
    pt: "Sabeis isto, meus amados irmãos. Todo o homem seja pronto para ouvir, tardio para falar, tardio para se irar.",
    keywords: ["listen", "speech", "wrath", "slow", "hear", "words"],
    theme: "speech",
  },
  {
    id: "phil-2-3",
    reference: "Philippians 2:3",
    kjv: "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves.",
    es: "Nada hagáis por contienda o por vanagloria; antes bien con humildad, estimando cada uno a los demás como superiores a él mismo.",
    pt: "Nada façais por contenda ou por vanglória, mas por humildade; cada um considere os outros superiores a si mesmo.",
    keywords: ["pride", "humble", "humility", "vainglory", "others"],
    theme: "character",
  },
  {
    id: "1pet-5-6",
    reference: "1 Peter 5:6-7",
    kjv: "Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time: casting all your care upon him; for he careth for you.",
    es: "Humillaos, pues, bajo la poderosa mano de Dios, para que él os ensalce cuando fuere tiempo: echando toda vuestra solicitud en él, porque él tiene cuidado de vosotros.",
    pt: "Humilhai-vos, pois, debaixo da potente mão de Deus, para que a seu tempo vos exalte; Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.",
    keywords: ["humble", "care", "anxiety", "worry", "cast"],
    theme: "faith",
  },
];

export const DEFAULT_SCRIPTURE = SCRIPTURE_CATALOG.find((entry) => entry.id === "james-1-22") ?? SCRIPTURE_CATALOG[0];

export function verseLocalized(entry: ScriptureEntry) {
  return {
    en: entry.kjv,
    es: entry.es.trim(),
    pt: entry.pt.trim(),
  };
}
